osx_image: xcode7.3
language: objective-c
before_install: 
  - gem install cocoapods xcpretty slather -N
  - xcrun instruments -w "iPhone 5 (9.3)" || echo "(Pre)Launched the simulator."
cache: cocoapods
script:
  - set -o pipefail && xcodebuild test -project LazyObject.xcodeproj -scheme "LazyObject" -destination "platform=iOS Simulator,name=iPhone 5,OS=9.3" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c
after_success:
  - slather coverage --ignore "../**/*/Xcode*" --scheme "LazyObject" LazyObject.xcodeproj